CREATE TABLE "PROJECT2"."ACCOUNT" 
   (	"NO" NUMBER(5,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30 BYTE), 
	"ID" VARCHAR2(30 BYTE), 
	"PWD" VARCHAR2(30 BYTE), 
	"NICK" VARCHAR2(30 BYTE), 
	"CRITIC_CHECK" NUMBER(1,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_ACCOUNT" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "PROJECT2"."ADMIN" 
   (	"ID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"A_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"M_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"R_NO" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ADMIN" PRIMARY KEY ("ID", "A_NO", "M_NO", "R_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_ACCOUNT_TO_ADMIN_1" FOREIGN KEY ("A_NO")
	  REFERENCES "PROJECT2"."ACCOUNT" ("NO") ENABLE, 
	 CONSTRAINT "FK_MOVIE_TO_ADMIN_1" FOREIGN KEY ("M_NO")
	  REFERENCES "PROJECT2"."MOVIE" ("M_NO") ENABLE, 
	 CONSTRAINT "FK_REVIEW_TO_ADMIN_1" FOREIGN KEY ("R_NO")
	  REFERENCES "PROJECT2"."REVIEW" ("R_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "PROJECT2"."CRITIC" 
   (	"NO" NUMBER(5,0) NOT NULL ENABLE, 
	"COMPANY" VARCHAR2(30 BYTE), 
	"CAREER" VARCHAR2(300 BYTE), 
	 CONSTRAINT "PK_CRITIC" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_ACCOUNT_TO_CRITIC_1" FOREIGN KEY ("NO")
	  REFERENCES "PROJECT2"."ACCOUNT" ("NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "PROJECT2"."MOVIE" 
   (	"M_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"M_TITLE" VARCHAR2(30 BYTE), 
	"M_DIRECT" VARCHAR2(30 BYTE), 
	"M_ACTOR" VARCHAR2(50 BYTE), 
	"M_GENRE" VARCHAR2(30 BYTE), 
	"M_RATE" NUMBER(3,2), 
	"M_AUDIENCE" VARCHAR2(30 BYTE), 
	"M_GRADE" VARCHAR2(30 BYTE), 
	"M_DATE" DATE, 
	"M_POSTER" VARCHAR2(300 BYTE), 
	 CONSTRAINT "PK_MOVIE" PRIMARY KEY ("M_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "PROJECT2"."REVIEW" 
   (	"R_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"M_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"A_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"R_NICK" VARCHAR2(30 BYTE), 
	"R_TITLE" VARCHAR2(30 BYTE), 
	"R_CONTENT" VARCHAR2(300 BYTE), 
	"R_DATE" DATE, 
	"R_REC" NUMBER(5,0), 
	 CONSTRAINT "PK_REVIEW" PRIMARY KEY ("R_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_MOVIE_TO_REVIEW_1" FOREIGN KEY ("M_NO")
	  REFERENCES "PROJECT2"."MOVIE" ("M_NO") ENABLE, 
	 CONSTRAINT "FK_ACCOUNT_TO_REVIEW_1" FOREIGN KEY ("A_NO")
	  REFERENCES "PROJECT2"."ACCOUNT" ("NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "PROJECT2"."REWARD" 
   (	"R_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"M_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"A_NO" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_REWARD" PRIMARY KEY ("R_NO", "M_NO", "A_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_REVIEW_TO_REWARD_1" FOREIGN KEY ("R_NO")
	  REFERENCES "PROJECT2"."REVIEW" ("R_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


CREATE TABLE POST (
	P_NO NUMBER(5) NOT NULL,
	NO NUMBER(5) NOT NULL,
	P_TITLE VARCHAR2(30) NULL,
	P_CONTENT VARCHAR2(300) NULL,
	P_DATE DATE NULL
);

CREATE TABLE P_COMMENT (
	C_NO NUMBER(5) NOT NULL,
	P_NO NUMBER(5) NOT NULL,
	NO NUMBER(5) NOT NULL,
	C_DATE DATE NULL
);

CREATE TABLE QA (
	Q_NO NUMBER(5) NOT NULL,
	NO NUMBER(5) NOT NULL,
	Q_CONTENT VARCHAR2(300) NULL,
	Q_DATE DATE NULL
);

CREATE TABLE INQUIRY (
	I_NO NUMBER(5) NOT NULL,
	Q_NO NUMBER(5) NOT NULL,
	I_CONTENT VARCHAR2(300) NULL,
	I_DATE DATE NULL
);

ALTER TABLE POST ADD CONSTRAINT PK_POST PRIMARY KEY (
	P_NO
);

ALTER TABLE P_COMMENT ADD CONSTRAINT PK_P_COMMENT PRIMARY KEY (
	C_NO
);

ALTER TABLE QA ADD CONSTRAINT PK_QA PRIMARY KEY (
	Q_NO
);

ALTER TABLE INQUIRY ADD CONSTRAINT PK_INQUIRY PRIMARY KEY (
	I_NO
);

ALTER TABLE ADMIN ADD CONSTRAINT FK_POST_TO_ADMIN_1 FOREIGN KEY (
	P_NO
)
REFERENCES POST (
	P_NO
);

ALTER TABLE ADMIN ADD CONSTRAINT FK_QA_TO_ADMIN_1 FOREIGN KEY (
	Q_NO
)
REFERENCES QA (
	Q_NO
);

ALTER TABLE POST ADD CONSTRAINT FK_ACCOUNT_TO_POST_1 FOREIGN KEY (
	NO
)
REFERENCES ACCOUNT (
	NO
);

ALTER TABLE P_COMMENT ADD CONSTRAINT FK_POST_TO_P_COMMENT_1 FOREIGN KEY (
	P_NO
)
REFERENCES POST (
	P_NO
);

ALTER TABLE P_COMMENT ADD CONSTRAINT FK_ACCOUNT_TO_P_COMMENT_1 FOREIGN KEY (
	NO
)
REFERENCES ACCOUNT (
	NO
);

ALTER TABLE QA ADD CONSTRAINT FK_ACCOUNT_TO_QA_1 FOREIGN KEY (
	NO
)
REFERENCES ACCOUNT (
	NO
);

ALTER TABLE INQUIRY ADD CONSTRAINT FK_QA_TO_INQUIRY_1 FOREIGN KEY (
	Q_NO
)
REFERENCES QA (
	Q_NO
);

CREATE SEQUENCE REVIEW_SEQ NOCACHE;
CREATE SEQUENCE MOVIE_SEQ NOCACHE;




